In [1]:
import numpy as np

# 將矩陣m裡大於等於1的數字都變成1，小於1的變成0

In [13]:
def yenlung(I, J):    
    L = np.random.randint(0,10,int(I*J)).reshape((I,J))
    print(L)
    L[L<1] = 0
    L[(L>=1)] = 1
    print(L)

In [15]:
yenlung(10,10)

[[9 3 8 5 2 0 1 6 0 2]
 [7 8 1 1 7 4 4 6 1 3]
 [7 3 6 9 4 4 9 9 9 2]
 [2 0 6 3 5 1 2 8 1 9]
 [3 3 8 6 6 0 4 9 2 0]
 [3 1 3 5 1 1 9 7 3 7]
 [2 5 3 2 5 2 8 0 6 5]
 [9 6 9 2 0 8 8 5 0 8]
 [3 4 8 3 2 0 1 6 1 8]
 [6 5 8 8 4 2 6 0 4 9]]
[[1 1 1 1 1 0 1 1 0 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1]
 [1 1 1 1 0 1 1 1 0 1]
 [1 1 1 1 1 0 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1]]


# Class grade average

In [30]:
A = np.random.randint(0,101,int(10*5)).reshape((10,5))
B = np.random.randint(0,101,int(10*5)).reshape((10,5))
C = np.random.randint(0,101,int(10*5)).reshape((10,5))
weights = np.array([[0.25],[0.25],[0.25],[0.15],[0.10]])

D = np.dot(A,weights)
E = np.dot(B,weights)
F = np.dot(C,weights)
print("A班平均/B班平均/C班平均")
np.array([np.sum(D)/10, np.sum(E)/10, np.sum(F)/10])

A班平均/B班平均/C班平均


array([ 46.415,  51.81 ,  54.84 ])