In [2]:
year = int(input("輸入一個年份: "))
if (year % 4) == 0:
    if (year % 100) == 0:
        if (year % 400) == 0:
            print("{0} 是閏年".format(year))   # 整百年能被400整除的是閏年
        else:
            print("{0} 不是閏年".format(year))
    else:
        print("{0} 是閏年".format(year))       # 非整百年能被4整除的為閏年
else:
    print("{0} 不是閏年".format(year))

輸入一個年份: 3000
3000 不是閏年


# 上面是第一題

# 下面是第二題

In [4]:
import numpy as np

In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
a+b

array([[2, 4],
       [6, 8]])

In [9]:
K = int(input("Which range do you want?(postive number)"))
m1 = np.random.randint(1,K,25).reshape((5,5))
m2 = np.random.randint(1,K,25).reshape((5,5))

Which range do you want?(postive number)100


In [21]:
def matrix_sum(m1,m2):
    print(m1)
    print(m2)
    return (m1+m2)

In [22]:
matrix_sum(m1,m2)

[[70  2  4 27 86]
 [51 11  2 65 29]
 [51 93 83 71 81]
 [40 65 50 46 32]
 [80 41 88 83 18]]
[[69 69 77 13 17]
 [20 41 98 72 59]
 [80 81 50 70 24]
 [69 66 45 31 37]
 [81 63 31 54 53]]


array([[139,  71,  81,  40, 103],
       [ 71,  52, 100, 137,  88],
       [131, 174, 133, 141, 105],
       [109, 131,  95,  77,  69],
       [161, 104, 119, 137,  71]])

# 下面是第三題

In [23]:
import pandas as pd

In [34]:
weights = {
"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
}
score = [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]

In [39]:
df = pd.DataFrame(weights, index=["國文", "英文", "數甲", "數乙", "物理", "化學", "生物", "歷史", "地理", "公民"])
df1 = df.T
df1["總分"] = df1.國文* 86.5 + df1.英文* 79.4 + df1.數甲* 88.2 + df1.數乙* 96.5 + df1.物理* 86.3 + df1.化學* 76.8 + df1.生物* 96.1 + df1.歷史* 78.5 + df1.地理* 82.4 + df1.公民* 88.6 
df1

國文   英文   數甲    數乙   物理   化學   生物   歷史   地理    公民       總分
公行系  1.0  1.5  0.0  1.25  0.0  0.0  0.0  0.0  0.0  1.25  436.975
國貿系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  481.550
土語系  2.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  1.0  0.00  589.200
應數系  1.0  1.0  1.5  0.00  1.0  1.0  0.0  0.0  0.0  0.00  461.300
教育系  1.5  2.0  0.0  1.25  0.0  0.0  0.0  1.0  1.0  0.00  570.075
會計系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  1.0  1.0  0.00  642.450
法律系  1.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  0.0  1.00  508.900
財政系  1.0  1.5  0.0  1.50  0.0  0.0  0.0  0.0  0.0  0.00  350.350
金融系  1.0  1.5  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  398.600